# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

u1 = User.create(name: "mustafa", password: "mustafa", password_confirmation: "mustafa", email: "mustafa@email.com")


p1 = Portfolio.create(name: "stocks long term", user_id: u1.id)
p2 = Portfolio.create(name: "crypto", user_id: u1.id)
p3 = Portfolio.create(name: "forex", user_id: u1.id)


s1 = Stock.create(open: 125, units: 2.4, symbol: "AMZ", portfolio_id: p1.id)
s2 = Stock.create(open: 28, units: 5, symbol: "AAPL", portfolio_id: p1.id)
s3 = Stock.create(open: 35, units: 8, symbol: "FB", portfolio_id: p1.id)
s4 = Stock.create(open: 158, units: 2.4, symbol: "ZM", portfolio_id: p2.id)
s5 = Stock.create(open: 271, units: 3.95, symbol: "MA", portfolio_id: p2.id)
s6 = Stock.create(open: 22, units: 45, symbol: "BAC", portfolio_id: p2.id)
s1 = Stock.create(open: 125, units: 2.4, symbol: "AMZ", portfolio_id: p1.id)
s2 = Stock.create(open: 28, units: 5, symbol: "AAPL", portfolio_id: p1.id)
s3 = Stock.create(open: 35, units: 8, symbol: "FB", portfolio_id: p1.id)
s4 = Stock.create(open: 158, units: 2.4, symbol: "ZM", portfolio_id: p2.id)
s5 = Stock.create(open: 271, units: 3.95, symbol: "MA", portfolio_id: p2.id)
s6 = Stock.create(open: 22, units: 45, symbol: "BAC", portfolio_id: p2.id)
s1 = Stock.create(open: 125, units: 2.4, symbol: "AMZ", portfolio_id: p1.id)
s2 = Stock.create(open: 28, units: 5, symbol: "AAPL", portfolio_id: p1.id)
s3 = Stock.create(open: 35, units: 8, symbol: "FB", portfolio_id: p1.id)
s4 = Stock.create(open: 158, units: 2.4, symbol: "ZM", portfolio_id: p2.id)
s5 = Stock.create(open: 271, units: 3.95, symbol: "MA", portfolio_id: p2.id)
s6 = Stock.create(open: 22, units: 45, symbol: "BAC", portfolio_id: p2.id)



Portfolio.create

raccomandation = Recommendation.create(name: 'dashboard') 

rs1 = RecommendedStock.create(price: 50, symbol: "GMED", recommendation_id: raccomandation.id)


InfoBuy.create(summary:"The idea of spinal surgery can be pretty terrifying. While outcomes are generally good and mistakes are rare, there's no question that there is little room for error. Luckily, the growing availability of minimally invasive techniques is turning formerly major surgeries into comparatively minor procedures. That's good news for an estimated roughly 16 million American adults who have serious, chronic back problems and for about 4.8 million people around the world who get back surgery each year.

  Still, minimally invasive surgery (MIS) is a broad term that varies widely in its implementation. While the first laparoscopic discectomy (removal of a spinal disc) took place in 1991, MIS is still used in a minority of spinal surgeries, in part because such operations require a great deal of specialized skill and experience on the part of the surgeon.
  
  This month's recommendation, Globus Medical (NYSE: GMED) is changing that. By combining advanced robotics, imaging, and artificial intelligence, the company and its ExcelsiusGPS platform are addressing more surgeries, improving outcomes, reducing complications, and making surgery more widely available. We think it's in the earliest stages of a major global opportunity.",  
  big_picture:"Globus is no newcomer to the spinal market. Founded in 2003, it makes more than 190 products for musculoskeletal surgeries, including screws, rods, and plates; bone fillers; and instruments used in various procedures. This is a steady, slow-growing business that still accounts for the vast majority of the company's revenue.

  But we're excited about another, newer part of the business. In 2014, Globus acquired Excelsius Surgical, which at the time was developing a robotic surgery platform. In 2017, the ExcelsiusGPS got FDA approval, launching as the first system with imaging, navigation, and robotics (which the company refers to as INR) in one platform.
  
  It might seem as though minimally invasive surgery and surgical robots are becoming commonplace these days. And for certain procedures, such as prostate surgery or hernia repair, that's true. But these are still early days when it comes to MIS for spinal procedures. And there's a reason for that.
  
  The earliest and simplest form of spinal MIS involved using fluoroscopy to image the patient's bone and tissue in real time, helping guide surgeon's movements and the placement of screws. But it requires exposing both patients and healthcare professionals to radiation — up to 10 or 12 times the amount involved in nonspinal imaging. That's an issue for patients but an even greater one for the medical professionals who are doing these surgeries day in and day out. For their own safety, many surgeons prefer to avoid MIS and do traditional open procedures.
  
  But while the ExcelsiusGPS can use fluoroscopy and intraoperative computerized tomography (CT), it can also build images prior to surgery and use other navigation tools to eliminate exposure to radiation. That's why robotic surgery has the potential to revolutionize spinal surgery.", 
  why_to_buy: "Reduced radiation exposure for patients and medical staff is far from the only advantage of ExcelsiusGPS. The system offers the potential for more accurate screw placement, improved procedure outcomes, less postsurgical pain, faster recovery time, and other benefits.

  Globus has started breaking its sales into enabling technologies (essentially the ExcelsiusGPS platform and related software) and musculoskeletal solutions (everything else). That's a pretty big vote of confidence, given that the 'everything else' category was 96% of revenue in the company's most recent quarter. The small robotics business has the potential not only to grow quickly but also to pull through sales of implantable devices that work with the system. Right now, however, it's still only a drop in the bucket next to the company's larger musculoskeletal business.
  
  We think that will change, particularly as the company broadens the ExcelsiusGPS to more spinal procedures. Now used mostly for screw placement, Globus is developing Excelsius for applications like spinal decompression, discectomy, rod bending, and more procedures around trauma and deformity. The company is also anticipating the launch of a module for cranial procedures in the current quarter and a module for interbody fusions later this year.
  
  Every new application magnifies the case for the ExcelsiusGPS. More hospitals will be encouraged to get the system but also to use Globus' related screws, rods, and other implantables with each procedure.", 
   leadership:"Globus' founder and executive chairman — and CEO until 2017 — is David Paul, a former executive at the DePuy Synthes orthopedic division of Johnson & Johnson (NYSE: JNJ) with a long track record of innovation in orthopedics. Although he stepped down from the CEO role rather suddenly due to an undisclosed health condition, he remains closely involved today. He still owns just over 23% of the company, aligning his interests closely with ours as shareholders.

   Day-to-day operations fall to CEO David Demski, who has also been with the company since its founding. Alongside Paul, he has spent 17 years building a company with industry-leading profitability (its net margins surpass even those of its large rivals) and that has thrived amid corporate behemoths by focusing squarely and exclusively on serving the spinal market.",  
   why_now:"The ExcelsiusGPS isn't the only system out there, even if it was the first with full INR capability. Globus is in a four-way competition with Medtronic (NYSE: MDT) (the Mazor X system), Zimmer Biomet (NYSE: ZBH) (the ROSA Spine system), and (to a lesser extent) NuVasive (NASDAQ: NUVA) (the PULSE system). Other companies like Stryker (NYSE: SYK) and J&J's Depuy Synthes division are also entering the market with competitive systems.

   While that puts a lot of pressure on the company, Globus has reported selling as many systems to new customers as to existing Globus clients. It's obvious that this is viewed as a big opportunity in the orthopedics market, and we believe Globus can take advantage of its head start and its exclusive focus on spinal procedures. But this is also a rising tide that should lift all boats: One study found that for the 2004-2007 period, only 13.2% of spinal procedures used any kind of MIS technique. By 2017, that had increased to nearly 25%. But it remains far from ubiquitous, and we believe most procedures can eventually benefit from some kind of robotic guidance and advanced imaging. Globus is a pure-play opportunity with advanced technology and a clear path forward.", 
   risk:"We mentioned competition, and it remains to be seen how well the company will navigate this. Enabling technology sales were up 125% in the third quarter but roughly flat in the fourth quarter and up only about 12% in the most recent quarter, as the impact of COVID-19 started to cut into capital equipment placements for many device companies. CEO Demski said the company is 'holding our own for sure' in a competitive environment, but we're looking for improvements in the platform to help it pull ahead.

   Robotic surgery is a big opportunity in the spinal space, but it's important to understand that it's happening in a challenging environment. Back pain is a leading cause of missed work, as well as one of the top three cost drivers for insurers. Unfortunately, surgery isn't always a sure-fire fix, and insurers are often reluctant to pay. That is particularly true of complex surgeries around deformities and degenerative disease, which is not currently the main focus of the ExcelsiusGPS system. But robotics is a chance to change the calculus in what is otherwise a relatively slow-growth market. If the ExcelsiusGPS doesn't remain a favored system, Globus could carry on as a relatively slow-growing, albeit nicely profitable, company.
   
   Finally, there are certainly going to be some short-term bumps in the road. The ExcelsiusGPS is an expensive system — around $1.5 million — and COVID-19 has already brought about a slowdown in spinal procedures as patients put off surgery, likely delaying purchase decisions at many hospitals. Management was expecting $850 million in overall revenue this year but has since withdrawn guidance.", 
 investment_value:"Spinal surgery is an area in which millimeter accuracy can be critical. Advanced imaging, computer-guided navigation, and precise robotic alignment are making surgeries more accurate and less invasive. That means less pain, less time in the hospital, improved outcomes, and even potential cost savings for insurers. Technological factors have limited the adoption of minimally invasive surgery in the spine market, but that's changing now. And we think it is inevitable that this will eventually become the mainstay of surgery as technology continues to improve.

 Globus Medical is off to a head start and remains laser-focused on the area. Already nicely profitable from its core business of spinal implants, instruments, and consumables, the ExcelsiusGPS robot can take the company to the next level. If you're looking for a lower-risk medtech company in your portfolio, Globus has got your back.", 
 recommended_stock_id:rs1.id )



 rs2 = RecommendedStock.create(price: 350, symbol: "NOW", recommendation_id: raccomandation.id)
 InfoBuy.create(summary:"Technology has transformed the business world in ways that few ever could have expected. It hasn't surprised us to see the most innovative, cutting-edge tech companies focus on coming up with IT solutions for common problems that their business clients face. What has been surprising, though, is how much every single business — from huge multinational enterprises to small Main Street businesses — stands to gain or lose based on making the best use of the tech resources at their disposal. 

  ServiceNow (NYSE: NOW) was quick to pick up on how important technology has become, but it also recognized the inherent challenges in staying on top of the latest advances. Most enterprises now rely on many different software packages to help them accomplish vital tasks, often turning to several vendors to meet all of their needs. Managing all that software can be a huge hassle. ServiceNow's platform-as-a-service offering makes it far easier for businesses to integrate and coordinate their tech tools in a single place, improving workflow and ensuring that enterprise clients can move smoothly toward embracing technology more fully.",  
  big_picture:"Businesses have always embraced technology as a way to boost productivity. By focusing workers' efforts on the areas in which they can add the most value, investing in technological advances has generally been a profitable move — as well as often building workforce morale by allowing people to have more engaging, meaningful jobs. 

  In the digital age, businesses face two competing challenges. On one hand, there are still many things that workers do using old-style manual processes that aren't efficient. Finding ways to automate those processes can unlock huge productivity gains. At the same time, technology has the potential to make jobs extremely complex, forcing workers to use a huge toolbox of different software programs and equipment to take advantage of the latest advances. To reduce the level of complexity in today's jobs, business enterprises have to find a way to use technology to manage technology. That's the promise of ServiceNow's platform, which essentially builds a bridge to let workers create workflows that use tech effectively while still doing their own jobs and contributing to the team effort.", 
  why_to_buy: "ServiceNow's Now Platform gives any worker the ability to automate processes by building digital workflow apps that offer users the same intuitive mobile-driven experiences as the apps they use in their personal lives. The platform connects users across the entire enterprise, and it allows them to integrate proprietary ServiceNow solutions and third-party platforms in a single place.

  Enterprise customers have flocked to ServiceNow's platform. The workplace tech specialist boasts more than 6,200 global enterprise customers, including almost 80% of all Fortune 500 companies. More than 900 of those customers have contracts that pay ServiceNow more than $1 million in annual revenue, and that number has grown 30% in just the past 12 months. In just the first three months of 2020, the company had 37 new transactions with more than $1 million in value, up by nearly half from its pace of growth a year ago.
  
  All those customers have helped ServiceNow's business thrive. Revenue grew 33% in 2019 and was higher by 34% year over year in the first quarter of 2020. Sales have climbed to a run rate of about $1 billion per quarter, and even more impressively, ServiceNow has turned the corner and become a profitable business.", 
   leadership:"ServiceNow founder Fred Luddy was instrumental in putting ServiceNow on the path toward success, as its CEO from 2004 to 2011 and then as chief product officer until 2016. At 65, Luddy has stepped back from day-to-day operations, but he remains chair of the company's board of directors. Moreover, with a stake of more than 750,000 shares worth more than $250 million at recent prices, Luddy's financial interest remains completely aligned with those of other shareholders.

   ServiceNow's success has attracted powerful executives interested in leading the company. In 2017, John Donahoe joined the company as CEO, with a resume that included the chief executive position at eBay (NASDAQ: EBAY) and a board chairmanship at PayPal Holdings (NASDAQ: PYPL). Donahoe's passion for embracing technology eventually led athletic products giant Nike (NYSE: NKE) to poach him to be its new CEO in October 2019. Now, former SAP (NYSE: SAP) CEO Bill McDermott leads ServiceNow. With a decade of experience leading the German tech giant, he has the vision to highlight the Now Platform's usefulness not just within IT departments but throughout entire business enterprises.",  
   why_now:"In particular, we're impressed with McDermott's ambition to take full advantage of ServiceNow's total addressable market. The new CEO has aspirations to tackle opportunities in machine learning and artificial intelligence as well as advanced business operations and asset management. In addition to tech resource management, ServiceNow sees itself embracing customer service management as well as managing field services in areas like supply chain and sales force deployment.

   Helping to drive this growth will be ServiceNow's innovation-focused NOWx unit, a place where the company looks at ideas for products and capabilities that its enterprise clients have asked ServiceNow to add to its platform. NOWx both provides creative ideas for future growth for ServiceNow and demonstrates its responsiveness to its customer base — two ingredients for success that we've seen work out well at other tech disruptors.", 
   risk:"As with every other business right now, the coronavirus pandemic is a source of uncertainty for ServiceNow. Yet McDermott believes that corporate leaders will be most hesitant to cut spending on digital transformation efforts, especially those that generate immediate benefits in adding value to their businesses. ServiceNow still sees subscription revenue growing 27% to 29% in 2020, representing just a 1% drop in guidance compared to what it expected back in January. 

   More broadly, the enterprise software space is extremely crowded, and competition is fierce. ServiceNow has carved out a solid niche, but as it seeks to explore adjacent opportunities, it'll run into more resistance from rivals. McDermott's decade of leadership at SAP should help ServiceNow immensely in overcoming this obstacle.
   
   Finally, investors in ServiceNow need to be comfortable with volatile share prices. ServiceNow's high valuation reflects its huge growth potential, and if the company faces business setbacks, the stock could react violently. This is nothing new to those familiar with investing in software-as-a-service (SaaS) companies, but it's easy to have your confidence shaken by a big stock drop that's out of line with the news that seems to cause it. Having the discipline to keep your resolve is essential with a stock like ServiceNow.", 
 investment_value:"I've had the good fortune to speak with countless business leaders over the years, and when tech executives I respect have good things to say about a company, I listen. That's been the case with ServiceNow, with executives at fellow tech upstarts like Okta (NASDAQ: OKTA) and Wix.com (NASDAQ: WIX) having mentioned the process automation company in several conversations. 

 With everything happening in the world right now, business enterprises need to embrace the best tools they can find to be as efficient and effective as possible. ServiceNow has those tools, and we think the stock will climb as more enterprise clients realize the value of the Now Platform.", 
 recommended_stock_id: rs2.id )


 rs3 = RecommendedStock.create(price: 600, symbol: "SHOP", recommendation_id: raccomandation.id)
 InfoBuy.create(summary:"Well-established companies and ambitious entrepreneurs alike have long recognized the power of the internet to help them attract customers and supplement the growth of their businesses.

  In the midst of what many fear could become the worst global pandemic in a century, though, doing business online is no longer something companies can adopt down the road or treat as just another part of an omnichannel strategy.
  
  Right now, e-commerce is the strategy -- and businesses that were late to the game are racing to adapt before it's too late.
  
  Since its beginning, Shopify (NYSE: SHOP) has helped businesses of all sizes make their way onto the internet. With a free trial and options that run from an entry-level subscription package for $9 a month to its premium Shopify Plus for high-volume merchants with the need for customized premium features, Shopify has built up a loyal customer base taking advantage of the key tech, logistics, marketing, and payments tools it provides. Once the worst of the coronavirus pandemic runs its course, the global economy's going to need a lot of new businesses to get started -- and Shopify will be there to help them, too.",  
  big_picture:"It didn't take long after the rise of the internet in the 1990s for businesses to realize its immense commercial potential. Unfortunately for budding e-commerce entrepreneurs, it took a lot longer for tools to emerge that would make their internet dreams a reality. Founder and CEO Tobi Lutke's frustration with the lack of help for would-be e-commerce business owners motivated him to start Shopify in 2004, and in just 15 years, the platform has attracted more than 1 million merchant customers from 175 countries across the globe.

  The beauty of Shopify's business model is that it effectively lets the platform provider participate in the success of its merchant clients. As merchants using the Shopify platform see their businesses grow, they need more services to keep up with rising demand. That leads them to upgrade to higher subscription levels, generating more revenue for Shopify. ", 
  why_to_buy: "Shopify has done a lot of things right to get to this moment, and it's better prepared than ever to make it through the challenges of the coronavirus crisis. The company has plenty of cash to finance operations and make growth-boosting acquisitions, and it now has significant positive operating cash flow coming in to further support the business. Revenue has kept growing at a strong pace, rising 47% in 2019 following a 59% jump in 2018.

  Luckily, Shopify hasn't let its success go to its head. The company has insisted on maintaining the highest-quality standards for its digital merchant platform, and the way Shopify treats its merchants like royalty stands in stark contrast to the reports of poor treatment of sellers by large online marketplace operators like Amazon.com (NASDAQ: AMZN). It's also led to extremely high retention rates of the most successful large merchants that use the premium Shopify Plus platform, and with more than a quarter of its monthly recurring revenue coming from those top clients, Shopify benefits greatly from their continued loyalty.
  
  Moreover, Shopify keeps building on its competitive advantage by adding new features to its tech-focused e-commerce platform. It recently launched its Shopify Email marketing tool for managing email sales campaigns, and its Shopify Fulfillment Network has continued to expand its scope, successfully helping thousands of merchants better manage the 2019 holiday season. The company has even recognized the value of helping businesses handle their in-person brick-and-mortar sales with the release of its Shopify Retail Kit.", 
   leadership:"Shopify is incredibly fortunate to have Tobi Lutke at the helm right now. I've had many interviews with him in the four years since I first recommended Shopify to Stock Advisor members, and every time I speak to him, I come away more impressed. With a deep passion to create more entrepreneurs, Lutke wants to run Shopify for the rest of his life.

   Lutke's wealth is tied to Shopify's success, with a roughly 7% economic stake worth around $3.4 billion at recent prices and giving the founder about a third of the voting power over the company. Yet each year, Lutke asks the board of directors whether they want him to keep leading Shopify forward. Moreover, the CEO has built a supportive work culture, and the company's gift of $1,000 to each employee to help create and optimize home offices is just the latest example of how Shopify has earned the loyalty of its workforce. Lutke's unique mix of insight and humility makes the Shopify founder stand out as a thought leader in the business world.",  
   why_now:"Our long-term perspective makes us look at companies a lot differently than most investors, and that's particularly evident with Shopify right now. The stock price has fallen by more than 25% just since mid-February, reflecting the fear surrounding stocks in general and the retail industry in particular. In the short run, a recession could put pressure on consumer spending broadly, hurting many of the businesses that rely on Shopify's platform. 

   However, the closure of so many retail store locations around the world has highlighted the critical importance of having a presence online. While having an e-commerce channel was once more a matter of convenience for shoppers, it's now become a necessity, and many retail businesses are surviving the coronavirus pandemic solely because they've continued to engage with customers via the internet. As that realization sinks in, Shopify will see many new customers come through the door -- and even after the worst of the crisis has ended, those merchants will remember how vital it was to have their e-commerce business to help sustain them. 
   
   Moreover, Shopify is looking to support its merchants directly. In an April 1 update, the company said it would offer an extended 90-day free trial to all standard plan signups, and make gift cards available on all plans for all merchants. Point-of-sale merchants will be able to get local in-store or curbside pickup and delivery, and Shopify will commit $200 million to its Shopify Capital program to help ailing businesses make it through the crisis.", 
   risk:"What remains to be seen, though, is how hard a hit Shopify's merchant client base will take due to the coronavirus pandemic. Even while the outbreak was largely confined to China, Shopify was keeping an eye on the potential impact that supply chain disruptions from Chinese manufacturers could have on its merchants.  In its update, Shopify said its positive momentum overall continued into January and February, and it expects that will be enough to overcome March headwinds to meet its first-quarter guidance for revenue and adjusted operating income. Beyond that, though, Shopify suspended its guidance for the remainder of 2020 as it looks to see what new challenges Shopify's merchant clients will face. 

   Shareholders also need to be prepared to keep seeing huge moves in Shopify's stock price. Even with immense revenue growth, the company's valuation of more than 30 times sales looks expensive in many investors' eyes. As much as we're inclined to look past Shopify's growing net losses -- the company did post an adjusted net profit in 2019 and is investing heavily in future growth -- many investors aren't as inclined to be patient about profitability, especially under the currently stressful conditions in the financial markets.", 
 investment_value:"Shopify is one of a select list of elite companies that have developed a technological advantage that's just getting stronger and stronger. Even though there are other companies looking to offer the same e-commerce services, Shopify's lead is so vast that it could take rivals years to catch up. For more than 1 million current Shopify customers -- and for the millions more that could soon join their ranks -- there's little reason to consider alternatives. That puts Shopify in a strong position even under crisis conditions and should bode well for the future.", 
 recommended_stock_id:rs3.id )

 rs4 = RecommendedStock.create(price: 160, symbol: "ZM", recommendation_id: raccomandation.id)
 InfoBuy.create(summary:"This month's recommendation is so in fitting with our current difficult times — it just makes so much sense — that I can't pass it up. The global COVID-19 pandemic will eventually subside, but it has become clear that its impact will linger. Just as nations need to be better prepared for future pandemics, private businesses (and individuals) need to be able to work more nimbly and keep the wheels turning even when it doesn't make sense, or isn't safe, for people to meet face to face. That is why Zoom Video Communications (NASDAQ: ZM) has defied the market crash and pushed near new highs.

 If this was all about panicked reaction, that might spell some short-term gains. But I believe that working from home, remote meetings, telemedicine, online education, and more are all going to become critical parts of life as we know it — if not for everyday living, then at least as an active contingency plan. In fact, we've been kicking this idea around for a while. Tom originally recommended Zoom in Stock Advisor last July, but that's also around the time that Tim Beyers, an analyst with Rule Breakers, pitched it to me for that service.",  
  big_picture:"As its name suggests, Zoom Video Communications offers an internet-based video (and audio/chat/content) communications platform that is used around the globe. It's certainly not the only platform for online telepresence. But if you've used it — and used its competitors — it feels like it should be. Here at The Motley Fool, we have a very geographically dispersed workforce at the best of times, and during the COVID-19 outbreak, we've all been working from home. We have a lot of personal experience with videoconferencing, and quite simply, nothing holds a candle to Zoom.

  And that's not just our opinion; the company has a Net Promoter Score of more than 70, which reflects very high satisfaction — something unusual for a technology platform, especially when you consider that among the many downsides of Zoom's competitors are spotty connections and other glitches that tend to drive people crazy.
  
  Why is Zoom better? Because the platform was built from the ground up for video, unlike everything that had preceded it, from WebEx to Microsoft's (NASDAQ: MSFT) Skype to Alphabet's (NASDAQ: GOOG) (NASDAQ: GOOGL) Google Hangouts. Founder and CEO Eric Yuan experienced that frustration directly as an employee of WebEx. It and other platforms were initially built to share slides and PowerPoint documents during audio calls, and it shows. Even after WebEx was acquired by Cisco (NASDAQ: CSCO) (Yuan eventually became corporate VP of engineering), there wasn't a real focus on improvement. Yuan said he eventually became embarrassed to go to work because customers were never happy. That's something he has directly addressed at Zoom.", 
  why_to_buy: "Zoom is truly built for a global audience — made to transmit high-quality video even over poor internet connections (it can handle up to 40% packet loss without noticeable loss of quality). That makes this software better able to truly and reliably connect the globe, making virtual meetings feel almost like they're face-to-face. In the past, that's been a nice-to-have feature for some businesses. In the future, it will be a must-have for a rising portion of the world.

  The spread of the platform has already been, if you'll excuse the term, viral. Many people download the app because they've been invited to a Zoom meeting, then learn how easy it is to use. That's a foot in the door.
  
  But Zoom isn't just souped-up Skype. It has a host of features meant to make communication work better, and customers are finding their way to them. For the past seven consecutive quarters, net dollar expansion rate has been over 130%. That means existing customers are not just sticking with the platform; they are, on average, spending 130% of what they did a year earlier.
  
  And not surprisingly for this kind of business, it is capital-light and highly scalable. Gross margin was nearly 80% even when the company only had a tenth of the sales it has today. (That'd be way back in 2016). That number is slowly pushing higher, and the company actually turned profitable in 2018. A cloud company that's profitable during this hypergrowth stage is almost unheard of, and it points to the kind of cash flow we think the company can eventually generate as it grows further.
  
  ", 
   leadership:"Eric Yuan dreamed up the idea for Zoom as a freshman in college in China, when he was frustrated by the 10-hour train rides he would take each week to visit his then-girlfriend (and current wife). It's a vision that percolated for well over a decade before he founded the company in 2011, and it has continued to evolve since the launch of the platform.

   The technology is great, and it has helped win Zoom customers from older and larger competitors. But what has really built the company is a focus on customer service and satisfaction. In the early days, Yuan would personally correspond with every person who decided to cancel service. When asked to name five things he wished he'd been told before launching his own company, Yuan's responses included the following three points:
   
   Your company's culture is the No. 1 most important thing to get right. Everything else flows from there.
   If your employees are not happy, nothing else at your company will go well.
   Find the investors who want to invest in you, not only in your business.
   That commitment to service and satisfaction is backed by his 11% stake in the company.",  
   why_now:"So why is now a good time to buy? In many ways, the urgency around an effective video communications platform is obvious. But what may not be so obvious are Zoom's opportunities as the best-in-class player at a critical time.

   Zoom benefits from a network effect. To use the platform, every party must be using the app. Zoom makes that as frictionless as possible — the app is free and easy to use for individuals participating in a conference. But as Zoom becomes the norm for businesses, there is added incentive to adopt it as a corporate platform.
   
   Meanwhile, Zoom is using its head start to jump further ahead with new features. It has already added hundreds since launch, from HIPAA security and compliance for telemedicine to integrations with numerous platforms including Salesforce (NYSE: CRM), Atlassian (NASDAQ: TEAM), and Slack (NYSE: WORK). The company anticipates many more.
   
   Indeed, management sees Zoom as a true unified communications platform, integrating technologies like augmented and virtual reality, automated note taking, and other AI features. Closer at hand, the company is going after the phone market with Zoom Phone, an enterprise cloud-based phone system (that works with third-party equipment) that integrates with other enterprise systems while folding in chat, video, and other features.", 
   risk:"Zoom is the only major platform to be built video first, but that doesn't mean it will be the last. Maintaining a technological lead in software is tough. We're not counting on Zoom to always be the runaway best platform for video conferencing in terms of pure quality and reliability; we're counting on it to maintain its lead through network effect and a continuing focus on customer service and customer satisfaction.

   Under Yuan's leadership, we think that will happen, but the company could always falter as pressure for growth intensifies or competitors encroach. And if Yuan, for any reason, is no longer part of the picture, we would take that as a red flag — Zoom is very much a reflection of his vision and the culture he has built.
   
   Beyond that, the stock remains very expensive at 49 times last year's revenue. That metric actually isn't much changed from a year ago, because sales have gone up alongside the stock. But eventually, sales need to climb more rapidly than share price.", 
 investment_value:"It's quite likely that a few of you have just recently found your way to Zoom as a result of the COVID-19 outbreak. We're all looking forward to life going back to normal as soon as possible, but that doesn't mean it will be exactly the same. The pandemic is a tragic illustration of how closely connected we are around the world — a sickness in Wuhan becomes an illness in Ohio with alarming speed. But Zoom is an illustration of the positivity of connection. That's going to have an impact long after we put this chapter behind us.", 
 recommended_stock_id:rs4.id )
 rs5 = RecommendedStock.create(price: 450, symbol: "DXCM", recommendation_id: raccomandation.id)
 InfoBuy.create(summary:"Even the ancient Greeks had some inkling of it: Diabetes is a problem of glucose control. The pancreas fails to make insulin or the body becomes less sensitive to it, leading to dangerous fluctuations in blood sugar levels. Insulin is a lifesaver, but this remains a disease of fine-tuning. Determining what to eat, when to eat, and exactly how much insulin to take and when can all make the difference between crudely managing the disease and truly putting it in the background.

  The ability for patients to check their own blood sugar levels emerged in the 1980s, and since 2010, glucose test strips have been accurate enough and easy enough to use that they've been recommended for all diabetes patients using insulin (and most others as well). They just require the user to prick a finger to get a drop of blood and then read a strip in a portable device. But what if patients simply knew their glucose level at all times, without the need to stop, get blood, and take a measurement?
  
  That's only become possible relatively recently, and this month's recommendation, DexCom (NASDAQ: DXCM), is the pioneer. It introduced the first real-time glucose monitoring system in 2006, but it has really been since 2012, when the company launched its G4 Platinum device, that continuous glucose monitoring (CGM) has started to catch on as a feasible tool for many patients. We think that diabetes care — and potentially even prediabetes care — will inevitably move toward these systems, much the way convenience made test strips a mainstay of disease management. That points to an incredible future for DexCom.
  
  ",  
  big_picture:"It's likely that diabetes has touched your life in some way. More than 30 million Americans have diabetes, according to the American Diabetes Association (ADA), including more than 12% of the adult population. Factor in prediabetes, and the figure is greater than 100 million. The vast majority of these patients have type 2 diabetes, which doesn't necessarily require insulin at first but often advances until insulin is needed. It certainly requires careful glucose control through diet, exercise, and other medications. Type 1 diabetes, meanwhile, represents less than 10% of diabetes cases but develops in childhood and requires lifelong daily insulin.

  Worldwide, the number of people with diabetes has quadrupled since 1980 and is expected to reach 700 million by 2045. The cost is crushing, with a total annual economic burden of $327 billion just in the U.S., according to the ADA. And the reason for the expense is not primarily the medicines and supplies used to manage the disease (only about 15% of the cost) but rather hospitalization and treatment of complications. Better managing the disease day to day is in the interest of patients, insurers, governments, and everyone else.
  
  That's why DexCom's CGM has been so eagerly embraced by patients and payers alike. By alerting patients to shifts in blood sugar, the devices can help them make better decisions about what and when to eat or how to optimize insulin intake. Since the 2012 launch of the G4 Platinum, sales have grown at a compound annual pace of 47%, reaching nearly $1.5 billion in 2019. Although the company just turned profitable last year, we expect profits and cash flow to climb quickly as it continues to see strong uptake of the current and future CGMs.", 
  why_to_buy: "DexCom certainly doesn't make the only CGM, but it has consistently had the most advanced, best-reviewed, and (anecdotally) best-loved devices. The G4 Platinum is still for sale, but it has been augmented by the G5 Mobile and G6 devices. While most CGMs require multiple fingerstick blood samples a day for calibration, the G6, launched in June 2018, does not. That's perhaps why management has reported that sales have far surpassed its expectations, making the company struggle to keep up with demand.

  CGMs are relatively complex, consisting of the receiver device that patients use to read results (although this can also be done with a smartphone) as well as a sensor and a transmitter that must be regularly replaced. You might say this is a razor-and-blade model, except that it's essentially all blade. This represents an ongoing revenue stream for the company.
  
  It's also fairly expensive. Sensors last about 10 days and cost about $400 for a pack of three. A transmitter lasts about three months and costs about $350. Luckily, insurance typically covers much of this expense for many patients.
  
  But this should improve with the launch of the G7, which is expected around the end of the year. A joint project with Verily, the life sciences arm of Alphabet (NASDAQ: GOOG) (NASDAQ: GOOGL), the G7 will be cheaper and more streamlined and will have sensors that last 14 to 15 days (instead of 10 for the G6). That should open up this technology to more people.", 
   leadership:"President, chairman, and CEO Kevin Sayer has led the company since 2015 and has overseen much of the company's recent upward trajectory, including the launches of the G5 and G6. In fact, he has been with the company since 2011, before the launch of the G4 Platinum that redefined the CGM space. Along with that, Sayer has shifted the company's focus from physicians to consumers, which we believe is responsible for much of the company's success in keeping up with the usability features that make the G6 so well regarded.

   It hasn't always gone smoothly. Around last Thanksgiving, the company had an extended server outage that prevented users from directly sharing DexCom data with their providers. The company chalked it up to growing pains — a change in data platform and technology that didn't go well — but Sayer also made a personal video apology to users, promising that the company could and would do better and outlining specific plans being put in place to make improvements and safeguards. We appreciate that kind of accountable leadership. DexCom's chief rivals are large, diverse device companies like Abbott and Medtronic that make all kinds of equipment for many different settings. DexCom serves one population only and is laser focused on it.
   
   ",  
   why_now:"DexCom has a tremendous long-term opportunity in a marketplace that is very early in what we think is a broad shift to the use of CGM devices, not just in type 1 but also in type 2 diabetes. U.S. penetration in the type 1 market is 35% to 40%, and it's about 15% for patients with intensive type 2 illness. The company has further opportunity here with less-intensive type 2 patients and overseas markets (where the company expects to see its fastest growth in 2020).

   That's been part of DexCom's growth story for the past few years, but there are more timely reasons to look at it right now. Last year, the company was able to aggressively begin shifting coverage of its devices toward being a pharmacy benefit rather than a piece of durable medical equipment. In 2019, it pushed sales through the pharmacy channel up 50%, and we expect more rapid switchover this year.
   
   Shifting to negotiated pharmacy benefits means DexCom actually gets less revenue per patient than it did through its wholesale channel, but it's a great long-term move for the company. It means lower out-of-pocket costs for most patients, which makes them less likely to try a cheaper alternative. It also expands the total number of patients eligible for use of the CGM, broadening the company's audience. That's not just because it becomes more affordable to patients but also because surveys show physicians are more likely to write a prescription for a CGM if it is covered under a pharmacy plan.
   
   The G6 also just became available to Medicare patients in early 2019, so we will see more uptake by this audience in 2020 — again, at somewhat lower revenue per patient than has been typical but well worth it for the added business.", 
   risk:"DexCom has led the way in features and accuracy pretty much as long as the CGM field has existed, and that has allowed the company to charge a premium price. But it's not clear that this advantage will always exist. Abbott's (NYSE: ABT) Freestyle Libre is a significantly cheaper CGM with similar capabilities that has proven very popular since its 2017 launch. Although it lags the G6 in features and accuracy, the FreeStyle Libre 2 is expected to narrow this gap. (It has already launched in Europe and could receive U.S. approval very soon, although unspecified delays have been reported.)

   Even with insurance, the G6 carries a fairly high cost burden for many patients, making it tempting — or downright necessary — for some to consider alternatives. We're hoping the G7 will keep DexCom in the lead technically while also bringing costs down. But if the company can't hit the right balance, and if larger competitors get more aggressive about this space, DexCom might have to sacrifice some of its margins or lose market share to rivals.
   
   ", 
 investment_value:"Diabetes is a reality for an alarmingly high proportion of the world, and managing the disease means more than providing insulin and guidance. This is a disease for which technology can have a huge impact on patient health and real-world costs. Being able to read blood glucose in real time means users can adapt in real time via diet and medication. Yet the technology is new enough that even most U.S. patients with type 1 diabetes haven't adopted it yet. We see a long tail of growth as it spreads to more people with type 2 diabetes, as well as people with prediabetes looking to avoid full-blown disease. DexCom is just a fraction of the size of its competitors, but it has taken control of this market and, we believe, will keep its lead.

 ", 
 recommended_stock_id: rs5.id)

#  InfoBuy.create(summary:"",  
#   big_picture:"", 
#   why_to_buy: "", 
#    leadership:"",  
#    why_now:"", 
#    risk:"", 
#  investment_value:"", 
#  recommended_stock_id: )